# Generated by Django 2.1.2 on 2018-10-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(blank=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('in_date', models.DateField()),
                ('operator', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Store.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='items_in',
            name='item',
        ),
        migrations.DeleteModel(
            name='Items_in',
        ),
    ]
