# Generated by Django 2.1.2 on 2018-10-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_total',
            name='location',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
