# Generated by Django 2.1.2 on 2018-10-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20181018_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsin',
            name='order_num',
        ),
    ]
