# Generated by Django 2.1.2 on 2018-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20181018_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items_Total',
            new_name='ItemsTotal',
        ),
    ]
