# Generated by Django 2.1.2 on 2018-11-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20181018_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsout',
            name='item_user',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
